[package]
name = "bm25-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bm25 = "2.1.0"
console_error_panic_hook = "0.1.7"
csv = "1.3.1"
gloo-net = "0.6.0"
leptos = { version = "0.7.0", features = ["csr"] }
web-sys = "0.3.74"
